### ISSUE TITLE
maintenance required 

### ISSUE THREAD

**Issue by PD-Kerman** [yusufklncc/HP-EliteBook-840-G5-Hackintosh#1]
Hellowww there :-) an hp 840g5 user here, really great project btw, and I sincerely hope this project could be maintained and upgraded continuously if u don’t mind, that means a lot to us. And thanks in advance 👍 
Best Regards

**Comment by yusufklncc** [comment]
Hi. thanks. Can you contact me from telegram?

**Comment by PD-Kerman** [comment]
> Hi. thanks. Can you contact me from telegram?

oh okay sure but i just sold my 840 g5 few weeks ago but still thank you for your contribution
