### ISSUE TITLE
 Freeze during installation

### ISSUE THREAD

**Issue by Blackhole4B11** [yusufklncc/HP-EliteBook-840-G5-Hackintosh#2]
Good morning,

I downloaded your EFI to try to install Ventura on this same laptop but unfortunately I am blocked during the first reboot during the installation. 
I boot on the installer, I manage to format my ssd via the disk utility and start the installation on the latter. 
But during the first restart on the "macOS installer" partition, the countdown remains stuck at 28 minutes (I left it running for more than 4 hours and it doesn't move).
I go through a usb3.0 ssd plugged into the right usb port (the one next to the HDMI port). 
Thank you in advance for your future elements.

**Comment by yusufklncc** [comment]
What is your SSD model?

**Comment by Blackhole4B11** [comment]
Thank you for your reply!
For the installation ("install key"), the ssd is an Intel 320 series 64Go (I also tried with 3 other E20 32Go ssds and with 5 different usb keys).
The ssd on which the system must be installed is the original ssd (Samsung PM981 256GB NVMe).

**Comment by yusufklncc** [comment]
(Samsung PM981 256GB NVMe) is not supported u have to change your SSD.

**Comment by Blackhole4B11** [comment]
Alright, so I'm going to order another one today.
Do you have a model to recommend to me?
I don't need a lot of capacity (250-265GB is fine for me, at worst I can take a 512GB max).

**Comment by yusufklncc** [comment]
https://www.amazon.com/WD_BLACK-SN770-Internal-Gaming-Solid/dp/B09QVP977F?th=1
Or 
https://www.amazon.com/dp/B087QTMXS7/?tag=pcsavvy05-20&th=1
You can use these ones.

**Comment by Blackhole4B11** [comment]
Thank you so much!!!
I will order the crucial and get back to you ASAP to update you on how things are going!

**Comment by Blackhole4B11** [comment]
So once again a big thank you!!!
Indeed, after changing the SSD, the installation was able to be done.
So problem solved!

**Comment by yusufklncc** [comment]
im glad it worked. Can you test if these work? I can't because I don't have this laptop anymore.![image](https://user-images.githubusercontent.com/78423442/232823631-26accf9b-ebea-4eef-9f2b-301af2ba9864.png)

**Comment by Blackhole4B11** [comment]
I will test in the next few days!

I will try to update OpenCore and the Kexts first.

**Comment by Yud-Bet** [comment]
Hi. I also downloaded your EFI but I cannot even boot to the installer. It's freezing at the apple logo and the progress bar cannot pass the half. I had the same hardware with you except 16GB of RAM, i5-8350u and my SSD is Samsung. This is my SSD info 
![image](https://user-images.githubusercontent.com/66458858/233401514-c3d07c9f-e581-41a3-9c03-fe99856324e3.png).
Could you please help me with that.

**Comment by yusufklncc** [comment]
we talked about it above.
![image](https://user-images.githubusercontent.com/78423442/233406364-d0948af3-d70d-413c-96a7-722ef50c3865.png)
SSD not supported.

**Comment by Yud-Bet** [comment]
Yah. I thought my ssd was different. Thank you. I think I should get a new one.

**Comment by Yud-Bet** [comment]
I replaced my ssd to WD blue but it doesn't work as well. It stuck at this ![IMG_20230422_150343.jpg](https://user-images.githubusercontent.com/66458858/233771376-3eecd4e4-7d80-47dc-aaaa-84fa7243d3a6.jpg)

**Comment by yusufklncc** [comment]
Change ur SMBIOS model MBP15,2 or 15,4 and try again.

**Comment by Yud-Bet** [comment]
I regenerated the SMBIOS and changed the config.plist but it still stuck at that screen. Let me say more detail about it. When I boot from usb, I see this err ![IMG_20230422_153410.jpg](https://user-images.githubusercontent.com/66458858/233774935-e41767ec-fefb-4dc7-b1b0-6e6e9db4ec79.jpg), but after that it continue to load. Then it is frozen at ![IMG_20230422_150343.jpg](https://user-images.githubusercontent.com/66458858/233775126-abd595d8-3cc6-4a68-a78c-ec4b11827845.jpg).
Does it give you any idea?

**Comment by yusufklncc** [comment]
https://github.com/yusufklncc/HP-EliteBook-840-G5-Hackintosh/releases/
Try with this

**Comment by Yud-Bet** [comment]
Do I need to regenerate the SMBIOS?

**Comment by Yud-Bet** [comment]
It's can go to the installer now. Thanks for your support.
